<?php
declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class LanternEventMigration extends AbstractMigration
{
    public function up(): void
    {
        $this->execute("START TRANSACTION;");

        $this->execute("INSERT INTO `ai_opponents` (`ai_id`, `rank`, `money`, `name`, `max_health`, `level`, `ninjutsu_skill`, `genjutsu_skill`, `taijutsu_skill`, `cast_speed`, `speed`, `strength`, `intelligence`, `willpower`, `moves`) VALUES
            (129, 2, 0, 'Kotengu', 0.70, 25, 0.65, 0.65, 0.65, 0.25, 0.25, 0.00, 0.10, 0.10, '[{\"battle_text\":\"In desperation, the [opponent] holds its treasure between itself and [player], stopping the attack in its tracks!\",\"power\":\"500\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"barrier\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"},{\"battle_text\":\"In desperation, the [opponent] holds its treasure between itself and [player], stopping the attack in its tracks!\",\"power\":\"500\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"barrier\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"},{\"battle_text\":\"Clawing and slashing with its razor-sharp claws, the [opponent] combines its ferocious melee attacks with graceful katana swings, creating a deadly dance of blades.\",\"power\":\"2.6\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"physical\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"}]'),
            (128, 4, 0, 'The Shadow Manipulator', 1.00, 100, 0.85, 0.85, 0.85, 0.60, 0.60, 0.00, 0.10, 0.10, '[{\"battle_text\":\"[opponent] creates an army of clones that burst into shadow upon destruction, binding [player] with an inescapable darkness.\",\"power\":\"6.5\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"projectile\",\"effect\":\"speed_nerf\",\"effect_amount\":\"50\",\"effect_length\":\"3\"},{\"battle_text\":\"[opponent] creates a veil of shadow, absorbing all incoming attacks and rendering it impervious to harm.\",\"power\":\"5.8\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"barrier\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"},{\"battle_text\":\"The battlefield becomes a nightmarish web of intangible spikes, conjured by [opponent]&#039;s mastery over shadows, each phantom spike sending waves of agonizing pain through [player]&#039;s body.\",\"power\":\"6\",\"jutsu_type\":\"genjutsu\",\"use_type\":\"projectile\",\"effect\":\"residual_damage\",\"effect_amount\":\"25\",\"effect_length\":\"4\"},{\"battle_text\":\"With a swift charge, [opponent] closes in on [player] slashing with a scythe forged from pure shadow.\",\"power\":\"5\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"physical\",\"effect\":\"residual_damage\",\"effect_amount\":\"25\",\"effect_length\":\"1\"}]'),
            (127, 4, 0, 'Shadow Oni', 0.85, 75, 0.80, 0.80, 0.80, 0.25, 0.25, 0.00, 0.10, 0.10, '[{\"battle_text\":\"Consumed by its primal rage, the [opponent] grows in size, its muscles bulging with raw power as it lets out a thunderous roar.\",\"power\":\"5\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"buff\",\"effect\":\"taijutsu_boost\",\"effect_amount\":\"50\",\"effect_length\":\"2\"},{\"battle_text\":\"With lightning-fast movements, the [opponent] charges at [player], its relentless flurry of blows aiming to shatter defenses and crush all opposition.\",\"power\":\"5\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"physical\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"}]'),
            (126, 3, 0, 'Mysterious Shinobi', 0.65, 50, 0.60, 0.60, 0.60, 0.35, 0.35, 0.00, 0.10, 0.10, '[{\"battle_text\":\"The [opponent] seamlessly disappears into the darkness, evading attacks with uncanny agility and launching surprise strikes from unexpected angles.\",\"power\":\"4.5\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"buff\",\"effect\":\"speed_boost\",\"effect_amount\":\"50\",\"effect_length\":\"3\"},{\"battle_text\":\"The [opponent] calls forth a horde of lesser yokai, overwhelming [player] with their combined assault.\",\"power\":\"4.5\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"physical\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"}]'),
            (125, 3, 0, 'Bloodthirsty Tengu', 0.70, 35, 0.65, 0.65, 0.65, 0.25, 0.25, 0.00, 0.10, 0.10, '[{\"battle_text\":\"The [opponent] leaps towards [player], drawing its katana in a swift motion, aiming to unleash a devastating strike.\",\"power\":\"4\",\"jutsu_type\":\"taijutsu\",\"use_type\":\"physical\",\"effect\":\"residual_damage\",\"effect_amount\":\"25\",\"effect_length\":\"2\"},{\"battle_text\":\"Clawing and slashing with its razor-sharp claws, the [opponent] combines its ferocious melee attacks with graceful katana swings, creating a deadly dance of blades.\",\"power\":\"3.6\",\"jutsu_type\":\"ninjutsu\",\"use_type\":\"physical\",\"effect\":\"none\",\"effect_amount\":\"0\",\"effect_length\":\"0\"}]');
        ");

        $this->execute("INSERT INTO `items` (`item_id`, `name`, `description`, `rank`, `purchase_type`, `purchase_cost`, `use_type`, `effect`, `effect_amount`) VALUES
            (119, 'Red Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (120, 'Blue Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (121, 'Violet Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (123, 'Shadow Essence', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (124, 'Sacred Red Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (125, 'Sacred Blue Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (126, 'Sacred Violet Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (127, 'Forbidden Jutsu Scroll', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (129, 'Gold Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0),
            (130, 'Sacred Gold Lantern', 'Event Item', 0, 2, 0, 4, 'unknown', 0);
        ");

        $this->execute("INSERT INTO `missions` (`mission_id`, `name`, `rank`, `mission_type`, `stages`, `money`, `rewards`) VALUES
            (111, 'Investigate Suspicious Markings', 3, 6, '[{\"action_type\":\"search\",\"action_data\":\"0\",\"location_radius\":\"2\",\"count\":\"0\",\"description\":\"While on patrol you spot signs of enemy shinobi! Search the area surrounding your village.\"},{\"action_type\":\"combat\",\"action_data\":\"126\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"You approach the pair of rogue shinobi, catching them in the midst of performing a summoning jutsu. You attack!\"},{\"action_type\":\"combat\",\"action_data\":\"127\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"As the remaining shinobi completes the summoning jutsu, a surge of dark energy fills the air. With a single blow, the Shadow Oni strikes down its would-be master before turning its attention toward you!\"}]', 200, '[{\"item_id\":\"119\",\"chance\":\"100\",\"quantity\":\"3\"},{\"item_id\":\"120\",\"chance\":\"50\",\"quantity\":\"1\"},{\"item_id\":\"121\",\"chance\":\"15\",\"quantity\":\"1\"}]'),
            (112, 'Begin Search', 1, 6, '[{\"action_type\":\"travel\",\"action_data\":\"0\",\"location_radius\":\"3\",\"count\":\"0\",\"description\":\"Follow the river and search for lanterns within 3 tiles of your village.\"}]', 30, '[{\"item_id\":\"119\",\"chance\":\"100\",\"quantity\":\"1\"},{\"item_id\":\"120\",\"chance\":\"20\",\"quantity\":\"1\"},{\"item_id\":\"121\",\"chance\":\"1\",\"quantity\":\"1\"}]'),
            (113, 'Follow Signs of Battle', 2, 6, '[{\"action_type\":\"travel\",\"action_data\":\"0\",\"location_radius\":\"2\",\"count\":\"0\",\"description\":\"While on patrol you discover scattered belongings and a trail of blood. Follow the trail to [action_data]!\"},{\"action_type\":\"combat\",\"action_data\":\"125\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"You find a group of villagers fleeing from a pair of bloodthirsty yokai! Protect the villagers!\"},{\"action_type\":\"combat\",\"action_data\":\"125\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"Defeat the second yokai!\"}]', 40, '[{\"item_id\":\"119\",\"chance\":\"100\",\"quantity\":\"2\"},{\"item_id\":\"120\",\"chance\":\"50\",\"quantity\":\"1\"},{\"item_id\":\"121\",\"chance\":\"3\",\"quantity\":\"1\"}]'),
            (114, 'Stop the Ritual', 4, 6, '[{\"action_type\":\"combat\",\"action_data\":\"125\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"Engage the mysterious shinobi!\"},{\"action_type\":\"combat\",\"action_data\":\"126\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"Engage the mysterious shinobi!\"},{\"action_type\":\"combat\",\"action_data\":\"127\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"As the second shinobi falls, a horde of yokai descend upon you and your allies!\"},{\"action_type\":\"combat\",\"action_data\":\"128\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"You fight your way through to the source of the chaos - a shadowy figure chanting from within the Font of Vitality!\"}]', 500, '[{\"item_id\":\"129\",\"chance\":\"100\",\"quantity\":\"1\"},{\"item_id\":\"123\",\"chance\":\"100\",\"quantity\":\"1\"}]'),
            (120, 'Hunt the Kotengu', 1, 6, '[{\"action_type\":\"search\",\"action_data\":\"0\",\"location_radius\":\"4\",\"count\":\"0\",\"description\":\"While on patrol you find a trail of coins and trinkets  - unmistakable signs of the Kotengu!<br>Search the area around your village for the Kotengu&#039;s lair.\"},{\"action_type\":\"combat\",\"action_data\":\"129\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"You sneak up on the Kotengu as it riffles through its bloodied bag of trinkets...\"}]', 30, '[{\"item_id\":\"119\",\"chance\":\"100\",\"quantity\":\"15\"},{\"item_id\":\"120\",\"chance\":\"100\",\"quantity\":\"3\"},{\"item_id\":\"121\",\"chance\":\"100\",\"quantity\":\"1\"},{\"item_id\":\"129\",\"chance\":\"100\",\"quantity\":\"1\"}]'),
            (119, 'Enter the Fray', 2, 6, '[{\"action_type\":\"combat\",\"action_data\":\"125\",\"location_radius\":\"0\",\"count\":\"0\",\"description\":\"As the final confrontation draws near, shinobi from all villages gather to face the relentless horde of yokai. Will you join the fray?\"}]', 200, '[{\"item_id\":\"119\",\"chance\":\"100\",\"quantity\":\"3\"},{\"item_id\":\"123\",\"chance\":\"5\",\"quantity\":\"1\"}]');
        ");

        $this->execute("COMMIT;");
    }
}
