<?php


return [
    [
        'code' => ':lesiregusta:',
        'image' => '<img src="./images/memes/like_a_sir_gusta.png" title=\':lesiregusta:\' alt=\':lesiregusta:\' />',
        'text' => ':like a sir gusta:',
        'public' => true,
    ],
    [
        'code' => ':lemadamgusta:',
        'image' => '<img src="./images/memes/like_a_lady_gusta.png" title=\':lemadamgusta:\' alt=\':lemadamgusta:\' />',
        'text' => ':like a lady gusta:',
        'public' => true,
    ],
    [
        'code' => ':lol:',
        'image' => '<img src="./images/memes/small_lol.png" title=\':lol:\' alt=\':lol:\' />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':yuno:',
        'image' => '<img src="./images/memes/yuno.png" title=\':yuno:\' alt=\':yuno:\' />',
        'text' => ':Y u no?:',
        'public' => true,
    ],
    [
        'code' => ':challengeaccepted:',
        'image' => '<img src="./images/memes/challenge_accepted.png" title=\':challengeaccepted:\' alt=\':challengeaccepted:\' />',
        'text' => ':challenge accepted:',
        'public' => true,
    ],
    [
        'code' => ':foreveralone:',
        'image' => '<img src="./images/memes/forever_alone.png" title=\':foreveralone:\' alt=\':foreveralone:\' />',
        'text' => ':forever alone:',
        'public' => true,
    ],
    [
        'code' => ':rageface:',
        'image' => '<img src="./images/memes/rage_face.png" title=\':rageface:\' alt=\':rageface:\' />',
        'text' => ':rage face:',
        'public' => true,
    ],
    [
        'code' => ':megusta:',
        'image' => '<img src="./images/memes/me_gusta.png" title=\':megusta:\' alt=\':megusta:\' />',
        'text' => ':me gusta:',
        'public' => true,
    ],
    [
        'code' => ':heckyeah:',
        'image' => '<img src="./images/memes/f_yeah.png" title=\':heckyeah:\' alt=\':heckyeah:\' />',
        'text' => ':heck yeah:',
        'public' => true,
    ],
    [
        'code' => ':okay:',
        'image' => '<img src="./images/memes/okay.png" title=\':okay:\' alt=\':okay:\' />',
        'text' => ':okay:',
        'public' => true,
    ],
    [
        'code' => ':screwthis:',
        'image' => '<img src="./images/memes/fts.png" title=\':screwthis:\' alt=\':screwthis:\' />',
        'text' => ':screw this:',
        'public' => true,
    ],
    [
        'code' => ':skyrimstan:',
        'image' => '<img src="./images/memes/skyrim_stan.png" title=\':skyrimstan:\' alt=\':skyrimstan:\' />',
        'text' => ':skyrim stan:',
        'public' => true,
    ],
    [
        'code' => ':asianfather:',
        'image' => '<img src="./images/memes/asian_father.png" title=\':asianfather:\' alt=\':asianfather:\' />',
        'text' => ':asian father:',
        'public' => true,
    ],
    [
        'code' => ':iknowthatfeel:',
        'image' => '<img src="./images/memes/i_know_that_feel_bro.png" title=\':iknowthatfeel:\' alt=\':iknowthatfeel:\' />',
        'text' => ':i know that feel:',
        'public' => true,
    ],
    [
        'code' => ':skeptical:',
        'image' => '<img src="./images/memes/skeptical.png" title=\':skeptical:\' alt=\':skeptical:\' />',
        'text' => ':skeptical:',
        'public' => true,
    ],
    [
        'code' => ':truestory:',
        'image' => '<img src="./images/memes/true_story.png" title=\':truestory:\' alt=\':truestory:\' />',
        'text' => ':true story:',
        'public' => true,
    ],
    [
        'code' => ':pokerface:',
        'image' => '<img src="./images/memes/poker_face.png" title=\':pokerface:\' alt=\':pokerface:\' />',
        'text' => ':poker face:',
        'public' => true,
    ],
    [
        'code' => ':awwyeah:',
        'image' => '<img src="./images/memes/aww_yeah.png" title=\':awwyeah:\' alt=\':awwyeah:\' />',
        'text' => ':aww yeah:',
        'public' => true,
    ],
    [
        'code' => ':ohgodwhy:',
        'image' => '<img src="./images/memes/oh_god_why.png" title=\':ohgodwhy:\' alt=\':ohgodwhy:\' />',
        'text' => ':oh god why:',
        'public' => true,
    ],
    [
        'code' => ':wut:',
        'image' => '<img src="./images/memes/wut.gif" title=\':wut:\' alt=\':wut:\' />',
        'text' => ':wut:',
        'public' => true,
    ],
    [
        'code' => ':areyouserious:',
        'image' => '<img src="./images/memes/are_you_serious.png" title=\':areyouserious:\' alt=\':areyouserious:\' />',
        'text' => ':are you serious:',
        'public' => true,
    ],
    [
        'code' => ':lololort:',
        'image' => '<img src="./images/memes/reverse_lol.png" />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':likeasir:',
        'image' => '<img src="./images/memes/like_a_sir.png" title=\':likeasir:\' alt=\':likeasir:\' />',
        'text' => ':like a sir:',
        'public' => true,
    ],
    [
        'code' => ':likealady:',
        'image' => '<img src="./images/memes/like_a_lady.png" title=\':likealady:\' alt=\':likealady:\' />',
        'text' => ':like a lady:',
        'public' => true,
    ],
    [
        'code' => ':allofthe:',
        'image' => '<img src="./images/memes/all_of_the.png" title=\':allofthe:\' alt=\':allofthe:\' />',
        'text' => ':all of the:',
        'public' => true,
    ],
    [
        'code' => ':grumpycat:',
        'image' => '<img src="./images/memes/grumpy_cat.png" title=\':grumpycat:\' alt=\':grumpycat:\' />',
        'text' => ':grumpy cat:',
        'public' => true,
    ],
    [
        'code' => ':notbad:',
        'image' => '<img src="./images/memes/not_bad.png" title=\':notbad:\' alt=\':notbad:\' />',
        'text' => ':not bad:',
        'public' => true,
    ],
    [
        'code' => ':whathasbeenseen:',
        'image' => '<img src="./images/memes/what_has_been_seen.png" title=\':whathasbeenseen:\' alt=\':whathasbeenseen:\' />',
        'text' => ':what has been seen:',
        'public' => true,
    ],
    [
        'code' => ':no:',
        'image' => '<img src="./images/memes/no.png" title=\':no:\' alt=\':no:\' />',
        'text' => ':no:',
        'public' => true,
    ],
    [
        'code' => ':motherofgod:',
        'image' => '<img src="./images/memes/mother_of_god.png" title=\':motherofgod:\' alt=\':motherofgod:\' />',
        'text' => ':mother of god:',
        'public' => true,
    ],
    [
        'code' => ':creepygusta:',
        'image' => '<img src="./images/memes/creepy_gusta.png" title=\':creepygusta:\' alt=\':creepygusta:\' />',
        'text' => ':creepy gusta:',
        'public' => true,
    ],
    [
        'code' => ':whatthe:',
        'image' => '<img src="./images/memes/what_the.png" title=\':whatthe:\' alt=\':whatthe:\' />',
        'text' => ':what the:',
        'public' => true,
    ],
    [
        'code' => ':insanitywolf:',
        'image' => '<img src="./images/memes/insanity_wolf.png" title=\':insanitywolf:\' alt=\':insanitywolf:\' />',
        'text' => ':insanity wolf:',
        'public' => true,
    ],
    [
        'code' => ':why:',
        'image' => '<img src="./images/memes/why.png" title=\':why:\' alt=\':why:\' />',
        'text' => ':why:',
        'public' => true,
    ],
    [
        'code' => ':yoda:',
        'image' => '<img src="./images/memes/yoda_meme.png" title=\':yoda:\' alt=\':yoda:\' />',
        'text' => ':yoda:',
        'public' => true,
    ],
    [
        'code' => ':alot:',
        'image' => '<img src="./images/memes/alot.png" title=\':alot:\' alt=\':alot:\' />',
        'text' => ':alot:',
        'public' => true,
    ],
    [
        'code' => ':herpderp:',
        'image' => '<img src="./images/memes/herp_derp.png" title=\':herpderp:\' alt=\':herpderp:\' />',
        'text' => ':herp derp:',
        'public' => true,
    ],
    [
        'code' => ':doge:',
        'image' => '<img src="./images/memes/doge.png" title=\':doge:\' alt=\':doge:\' />',
        'text' => ':doge:',
        'public' => true,
    ],
    [
        'code' => ':catte:',
        'image' => '<img src="./images/memes/catte.png" title=\':catte:\' alt=\':catte:\' />',
        'text' => ':catte:',
        'public' => true,
    ],
    [
        'code' => ':confessionbear:',
        'image' => '<img src="./images/memes/confession_bear.png" title=\':confessionbear:\' alt=\':confessionbear:\' />',
        'text' => ':confession bear:',
        'public' => true,
    ],
    [
        'code' => ':kappa:',
        'image' => '<img src="./images/memes/kappa.png" title=\':kappa:\' alt=\':kappa:\' />',
        'text' => ':kappa:',
        'public' => true,
    ],
    [
        'code' => ':howaboutno:',
        'image' => '<img src="./images/memes/how_about_no.png" title=\':howaboutno:\' alt=\':howaboutno:\' />',
        'text' => ':how about no:',
        'public' => true,
    ],
    [
        'code' => ':awkwardseal:',
        'image' => '<img src="./images/memes/awkward_seal.png" title=\':awkwardseal:\' alt=\':awkwardseal:\' />',
        'text' => ':awkward seal:',
        'public' => true,
    ],
    [
        'code' => ':wegotabadass:',
        'image' => '<img src="./images/memes/watch_out_we_got_a_badass.png" title=\':wegotabadass:\' alt=\':wegotabadass:\' />',
        'text' => ':watch out we got a badass here:',
        'public' => true,
    ],
    [
        'code' => ':facepalm:',
        'image' => '<img src="./images/memes/facepalm.png" title=\':facepalm:\' alt=\':facepalm:\' />',
        'text' => ':facepalm:',
        'public' => true,
    ],
    [
        'code' => ':opieop:',
        'image' => '<img src="./images/memes/opieop.png" title=\':opieop:\' alt=\':opieop:\' />',
        'text' => ':opieop:',
        'public' => true,
    ],
    [
        'code' => ':oskomodo:',
        'image' => '<img src="./images/memes/oskomodo.png" title=\':oskomodo:\' alt=\':oskomodo:\' />',
        'text' => ':oskomodo:',
        'public' => true,
    ],
    [
        'code' => ':babyrage:',
        'image' => '<img src="./images/memes/babyrage.png" title=\':babyrage:\' alt=\':babyrage:\' />',
        'text' => ':babyrage:',
        'public' => true,
    ],
    [
        'code' => ':pogchamp:',
        'image' => '<img src="./images/memes/pogchamp2.png" title=\':pogchamp:\' alt=\':pogchamp:\' />',
        'text' => ':pogchamp:',
        'public' => true,
    ],
    [
        'code' => ':smileyderp:',
        'image' => '<img src="./images/memes/smiley_derp.png" title=\':smileyderp:\' alt=\':smileyderp:\' />',
        'text' => ':smileyderp:',
        'public' => true,
    ],
    [
        'code' => ':aliensguy:',
        'image' => '<img src="./images/memes/aliens_guy.png" title=\':aliensguy:\' alt=\':aliensguy:\' />',
        'text' => ':aliensguy:',
        'public' => true,
    ],
    [
        'code' => ':kreygasm:',
        'image' => '<img src="./images/memes/kreygasm.png" title=\':kreygasm:\' alt=\':kreygasm:\' />',
        'text' => ':kreygasm:',
        'public' => true,
    ],
    [
        'code' => ':seemsgood:',
        'image' => '<img src="./images/memes/seems_good.png" title=\':seemsgood:\' alt=\':seemsgood:\' />',
        'text' => ':seems good:',
        'public' => true,
    ],
    [
        'code' => ':vaultboy:',
        'image' => '<img src="./images/memes/vault_boy.png" title=\':vaultboy:\' alt=\':vaultboy:\' />',
        'text' => ':vault boy:',
        'public' => true,
    ],
    [
        'code' => ':heyguys:',
        'image' => '<img src="./images/memes/hey_guys.png" title=\':heyguys:\' alt=\':heyguys:\' />',
        'text' => ':hey guys:',
        'public' => true,
    ],
    [
        'code' => ':4head:',
        'image' => '<img src="./images/memes/4head.png" title=\':4head:\' alt=\':4head:\' />',
        'text' => ':4head:',
        'public' => true,
    ],
    [
        'code' => ':tellmemore:',
        'image' => '<img src="./images/memes/tell_me_more.png" title=\':tellmemore:\' alt=\':tellmemore:\' />',
        'text' => ':tell me more:',
        'public' => true,
    ],
    [
        'code' => ':victory:',
        'image' => '<img src="./images/memes/victory.png" title=\':victory:\' alt=\':victory:\' />',
        'text' => ':victory:',
        'public' => true,
    ],
    [
        'code' => ':everywhere:',
        'image' => '<img src="./images/memes/everywhere.png" title=\':everywhere:\' alt=\':everywhere:\' />',
        'text' => ':everywhere:',
        'public' => true,
    ],
    [
        'code' => ':notlikethis:',
        'image' => '<img src="./images/memes/not_like_this.png" title=\':notlikethis:\' alt=\':notlikethis:\' />',
        'text' => ':not like this:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodman:',
        'image' => '<img src="./images/memes/feels_good_man.png" title=\':feelsgoodman:\' alt=\':feelsgoodman:\' />',
        'text' => ':feels good man:',
        'public' => true,
    ],
    [
        'code' => ':feelsbadman:',
        'image' => '<img src="./images/memes/feels_bad_man.png" title=\':feelsbadman:\' alt=\':feelsbadman:\' />',
        'text' => ':feels bad man:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodbad:',
        'image' => '<img src="./images/memes/feels_good_bad.png" title=\':feelsgoodbad:\' alt=\':feelsgoodbad:\' />',
        'text' => ':feels good bad:',
        'public' => true,
    ],
    [
        'code' => ':confused:',
        'image' => '<img src="./images/memes/confused.png" title=\':confused:\' alt=\':confused:\' />',
        'text' => ':confused:',
        'public' => true,
    ],
    [
        'code' => ':letsrumble:',
        'image' => '<img src="./images/memes/lets_rumble.png" title=\':letsrumble:\' alt=\':letsrumble:\' />',
        'text' => ':letsrumble:',
        'public' => true,
    ],
    [
        'code' => ':thisisfine:',
        'image' => '<img src="./images/memes/this_is_fine.png"
                title=\':thisisfine:\' alt=\':thisisfine:\' />',
        'text' => ':this is fine:',
        'public' => true,
    ],

    [
        'code' => ':notmybusiness:',
        'image' => '<img src="./images/memes/none_of_my_business.png"
                title=\':notmybusiness:\' alt=\':notmybusiness:\' />',
        'text' => ':none of my business:',
        'public' => true,
    ],
    [
        'code' => ':youdontsay:',
        'image' => '<img src="./images/memes/you_dont_say.png"
                title=\':youdontsay:\' alt=\':youdontsay:\' />',
        'text' => ':you don\'t say:',
        'public' => true,
    ],
    [
        'code' => ':callinglsm:',
        'image' => '<img src="./images/memes/arctic6.png" />',
        'text' => ':calling lsm:',
        'public' => true,
    ],
    [
        'code' => ':guessilldie:',
        'image' => '<img src="./images/memes/feels_old_man.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':surprisedpikachu:',
        'image' => '<img src="./images/memes/surprised_pikachu.png" />',
        'text' => ':surprised pikachu:',
        'public' => true,
    ],
    [
        'code' => ':whitelotus:',
        'image' => '<img src="./images/memes/iroh.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':dogekek:',
        'image' => "<img src='./images/memes/doge_kek.png' style='width:64px;height:64px;' />",
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':feelschatman:',
        'image' => "<img src='./images/memes/feelschatman.png' style='width:64px;height:64px;' />",
        'text' => ':feelschatman:',
        'public' => true,
    ],
    [
        'code' => ':shukaku:',
        'image' => "<img src='./images/memes/shukaku_kun.png' style='width:64px;height:64px;' />",
        'text' => ':shukaku:',
        'public' => true,
    ],
    [
        'code' => ':matatabi:',
        'image' => "<img src='./images/memes/matatabi_kun.png' style='width:64px;height:64px;' />",
        'text' => ':matatabi:',
        'public' => true,
    ],
    [
        'code' => ':isobu:',
        'image' => "<img src='./images/memes/isobu_kun.png' style='width:64px;height:64px;' />",
        'text' => ':isobu:',
        'public' => true,
    ],
    [
        'code' => ':goku:',
        'image' => "<img src='./images/memes/goku_kun.png' style='width:64px;height:64px;' />",
        'text' => ':goku:',
        'public' => true,
    ],
    [
        'code' => ':kokuo:',
        'image' => "<img src='./images/memes/kokuo_kun.png' style='width:64px;height:64px;' />",
        'text' => ':kokuo:',
        'public' => true,
    ],
    [
        'code' => ':saiken:',
        'image' => "<img src='./images/memes/saiken_kun.png' style='width:64px;height:64px;' />",
        'text' => ':saiken:',
        'public' => true,
    ],
    [
        'code' => ':chomei:',
        'image' => "<img src='./images/memes/chomei_kun.png' style='width:64px;height:64px;' />",
        'text' => ':chomei:',
        'public' => true,
    ],
    [
        'code' => ':gyuki:',
        'image' => "<img src='./images/memes/gyuki_kun.png' style='width:64px;height:64px;' />",
        'text' => ':gyuki:',
        'public' => true,
    ],
    [
        'code' => ':kurama:',
        'image' => "<img src='./images/memes/kurama_kun.png' style='width:64px;height:64px;' />",
        'text' => ':kurama:',
        'public' => true,
    ],
    [
        'code' => ':narutoooo:',
        'image' => "<img src='./images/memes/narutoooo.png' style='width:64px;height:64px;' />",
        'text' => ':narutoooo:',
        'public' => true,
    ],
    [
        'code' => ':sasukeeee:',
        'image' => "<img src='./images/memes/sasukeeee.png' style='width:64px;height:64px;' />",
        'text' => ':sasukeeee:',
        'public' => true,
    ],
    [
        'code' => ':catjam:',
        'image' => "<img src='./images/memes/cat-jam.gif' style='width:64px;height:64px;' />",
        'text' => ':catjam:',
        'public' => true,
    ],
    [
        'code' => ':sokkatribe:',
        'image' => "<img src='./images/memes/sokkatribe.gif' />",
        'text' => ':Guess Sokka will die too:',
        'public' => true,
    ],
    [
        'code' => ':selfmedal:',
        'image' => "<img src='./images/memes/lsm_self_medal.png' />",
        'text' => ':lsm giving himself a medal:',
        'public' => true,
    ],
];

