<?php


return [
    [
        'code' => ':lesiregusta:',
        'image' => ' />',
        'text' => ':like a sir gusta:',
        'public' => true,
    ],
    [
        'code' => ':lemadamgusta:',
        'image' => ' />',
        'text' => ':like a lady gusta:',
        'public' => true,
    ],
    [
        'code' => ':lol:',
        'image' => '<img src="./images/memes/lol.png" title=\':lol:\' alt=\':lol:\' />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':yuno:',
        'image' => ' />',
        'text' => ':Y u no?:',
        'public' => true,
    ],
    [
        'code' => ':challengeaccepted:',
        'image' => ' />',
        'text' => ':challenge accepted:',
        'public' => true,
    ],
    [
        'code' => ':foreveralone:',
        'image' => ' />',
        'text' => ':forever alone:',
        'public' => true,
    ],
    [
        'code' => ':rageface:',
        'image' => ' />',
        'text' => ':rage face:',
        'public' => true,
    ],
    [
        'code' => ':megusta:',
        'image' => ' />',
        'text' => ':me gusta:',
        'public' => true,
    ],
    [
        'code' => ':heckyeah:',
        'image' => ' />',
        'text' => ':heck yeah:',
        'public' => true,
    ],
    [
        'code' => ':okay:',
        'image' => ' />',
        'text' => ':okay:',
        'public' => true,
    ],
    [
        'code' => ':screwthis:',
        'image' => ' />',
        'text' => ':screw this:',
        'public' => true,
    ],
    [
        'code' => ':skyrimstan:',
        'image' => ' />',
        'text' => ':skyrim stan:',
        'public' => true,
    ],
    [
        'code' => ':asianfather:',
        'image' => ' />',
        'text' => ':asian father:',
        'public' => true,
    ],
    [
        'code' => ':iknowthatfeel:',
        'image' => ' />',
        'text' => ':i know that feel:',
        'public' => true,
    ],
    [
        'code' => ':skeptical:',
        'image' => ' />',
        'text' => ':skeptical:',
        'public' => true,
    ],
    [
        'code' => ':truestory:',
        'image' => ' />',
        'text' => ':true story:',
        'public' => true,
    ],
    [
        'code' => ':pokerface:',
        'image' => ' />',
        'text' => ':poker face:',
        'public' => true,
    ],
    [
        'code' => ':awwyeah:',
        'image' => ' />',
        'text' => ':aww yeah:',
        'public' => true,
    ],
    [
        'code' => ':ohgodwhy:',
        'image' => ' />',
        'text' => ':oh god why:',
        'public' => true,
    ],
    [
        'code' => ':wut:',
        'image' => ' />',
        'text' => ':wut:',
        'public' => true,
    ],
    [
        'code' => ':areyouserious:',
        'image' => ' />',
        'text' => ':are you serious:',
        'public' => true,
    ],
    [
        'code' => ':lololort:',
        'image' => '<img src="../images/memes/reverse_lol.png" />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':likeasir:',
        'image' => ' />',
        'text' => ':like a sir:',
        'public' => true,
    ],
    [
        'code' => ':likealady:',
        'image' => ' />',
        'text' => ':like a lady:',
        'public' => true,
    ],
    [
        'code' => ':allofthe:',
        'image' => ' />',
        'text' => ':all of the:',
        'public' => true,
    ],
    [
        'code' => ':grumpycat:',
        'image' => ' />',
        'text' => ':grumpy cat:',
        'public' => true,
    ],
    [
        'code' => ':notbad:',
        'image' => ' />',
        'text' => ':not bad:',
        'public' => true,
    ],
    [
        'code' => ':whathasbeenseen:',
        'image' => ' />',
        'text' => ':what has been seen:',
        'public' => true,
    ],
    [
        'code' => ':no:',
        'image' => ' />',
        'text' => ':no:',
        'public' => true,
    ],
    [
        'code' => ':motherofgod:',
        'image' => ' />',
        'text' => ':mother of god:',
        'public' => true,
    ],
    [
        'code' => ':creepygusta:',
        'image' => ' />',
        'text' => ':creepy gusta:',
        'public' => true,
    ],
    [
        'code' => ':whatthe:',
        'image' => ' />',
        'text' => ':what the:',
        'public' => true,
    ],
    [
        'code' => ':insanitywolf:',
        'image' => ' />',
        'text' => ':insanity wolf:',
        'public' => true,
    ],
    [
        'code' => ':why:',
        'image' => ' />',
        'text' => ':why:',
        'public' => true,
    ],
    [
        'code' => ':yoda:',
        'image' => ' />',
        'text' => ':yoda:',
        'public' => true,
    ],
    [
        'code' => ':alot:',
        'image' => ' />',
        'text' => ':alot:',
        'public' => true,
    ],
    [
        'code' => ':herpderp:',
        'image' => ' />',
        'text' => ':herp derp:',
        'public' => true,
    ],
    [
        'code' => ':doge:',
        'image' => ' />',
        'text' => ':doge:',
        'public' => true,
    ],
    [
        'code' => ':catte:',
        'image' => ' />',
        'text' => ':catte:',
        'public' => true,
    ],
    [
        'code' => ':confessionbear:',
        'image' => ' />',
        'text' => ':confession bear:',
        'public' => true,
    ],
    [
        'code' => ':kappa:',
        'image' => ' />',
        'text' => ':kappa:',
        'public' => true,
    ],
    [
        'code' => ':howaboutno:',
        'image' => ' />',
        'text' => ':how about no:',
        'public' => true,
    ],
    [
        'code' => ':awkwardseal:',
        'image' => ' />',
        'text' => ':awkward seal:',
        'public' => true,
    ],
    [
        'code' => ':wegotabadass:',
        'image' => ' />',
        'text' => ':watch out we got a badass here:',
        'public' => true,
    ],
    [
        'code' => ':facepalm:',
        'image' => ' />',
        'text' => ':facepalm:',
        'public' => true,
    ],
    [
        'code' => ':opieop:',
        'image' => ' />',
        'text' => ':opieop:',
        'public' => true,
    ],
    [
        'code' => ':oskomodo:',
        'image' => ' />',
        'text' => ':oskomodo:',
        'public' => true,
    ],
    [
        'code' => ':babyrage:',
        'image' => ' />',
        'text' => ':babyrage:',
        'public' => true,
    ],
    [
        'code' => ':pogchamp:',
        'image' => ' />',
        'text' => ':pogchamp:',
        'public' => true,
    ],
    [
        'code' => ':smileyderp:',
        'image' => ' />',
        'text' => ':smileyderp:',
        'public' => true,
    ],
    [
        'code' => ':aliensguy:',
        'image' => ' />',
        'text' => ':aliensguy:',
        'public' => true,
    ],
    [
        'code' => ':kreygasm:',
        'image' => ' />',
        'text' => ':kreygasm:',
        'public' => true,
    ],
    [
        'code' => ':seemsgood:',
        'image' => ' />',
        'text' => ':seems good:',
        'public' => true,
    ],
    [
        'code' => ':vaultboy:',
        'image' => ' />',
        'text' => ':vault boy:',
        'public' => true,
    ],
    [
        'code' => ':heyguys:',
        'image' => ' />',
        'text' => ':hey guys:',
        'public' => true,
    ],
    [
        'code' => ':4head:',
        'image' => ' />',
        'text' => ':4head:',
        'public' => true,
    ],
    [
        'code' => ':tellmemore:',
        'image' => ' />',
        'text' => ':tell me more:',
        'public' => true,
    ],
    [
        'code' => ':victory:',
        'image' => ' />',
        'text' => ':victory:',
        'public' => true,
    ],
    [
        'code' => ':everywhere:',
        'image' => ' />',
        'text' => ':everywhere:',
        'public' => true,
    ],
    [
        'code' => ':notlikethis:',
        'image' => ' />',
        'text' => ':not like this:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodman:',
        'image' => ' />',
        'text' => ':feels good man:',
        'public' => true,
    ],
    [
        'code' => ':feelsbadman:',
        'image' => ' />',
        'text' => ':feels bad man:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodbad:',
        'image' => ' />',
        'text' => ':feels good bad:',
        'public' => true,
    ],
    [
        'code' => ':confused:',
        'image' => ' />',
        'text' => ':confused:',
        'public' => true,
    ],
    [
        'code' => ':letsrumble:',
        'image' => ' />',
        'text' => ':letsrumble:',
        'public' => true,
    ],
    [
        'code' => ':thisisfine:',
        'image' => ' />\'',
        'text' => ':this is fine:',
        'public' => true,
    ],

    [
        'code' => ':notmybusiness:',
        'image' => ' />\'',
        'text' => ':none of my business:',
        'public' => true,
    ],
    [
        'code' => ':youdontsay:',
        'image' => ' />\'',
        'text' => ':you don\'t say:',
        'public' => true,
    ],
    [
        'code' => ':callinglsm:',
        'image' => '<img src="../images/memes/arctic6.png" />',
        'text' => ':calling lsm:',
        'public' => true,
    ],
    [
        'code' => ':guessilldie:',
        'image' => '<img src="../images/memes/feels_old_man.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':surprisedpikachu:',
        'image' => '<img src="../images/memes/surprised_pikachu.png" />',
        'text' => ':surprised pikachu:',
        'public' => true,
    ],
    [
        'code' => ':whitelotus:',
        'image' => '<img src="../images/memes/iroh.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':dogekek:',
        'image' => "<img src='../images/memes/doge_kek.png' style='width:64px;height:64px;' />",
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':feelschatman:',
        'image' => "<img src='../images/memes/feelschatman.png' style='width:64px;height:64px;' />",
        'text' => ':feelschatman:',
        'public' => true,
    ],
    [
        'code' => ':shukaku:',
        'image' => "<img src='./images/memes/shukaku_kun.png' style='width:64px;height:64px;' />",
        'text' => ':shukaku:',
        'public' => true,
    ],
    [
        'code' => ':matatabi:',
        'image' => "<img src='./images/memes/matatabi_kun.png' style='width:64px;height:64px;' />",
        'text' => ':matatabi:',
        'public' => true,
    ],
    [
        'code' => ':isobu:',
        'image' => "<img src='./images/memes/isobu_kun.png' style='width:64px;height:64px;' />",
        'text' => ':isobu:',
        'public' => true,
    ],
    [
        'code' => ':goku:',
        'image' => "<img src='./images/memes/goku_kun.png' style='width:64px;height:64px;' />",
        'text' => ':goku:',
        'public' => true,
    ],
    [
        'code' => ':kokuo:',
        'image' => "<img src='./images/memes/kokuo_kun.png' style='width:64px;height:64px;' />",
        'text' => ':kokuo:',
        'public' => true,
    ],
    [
        'code' => ':saiken:',
        'image' => "<img src='./images/memes/saiken_kun.png' style='width:64px;height:64px;' />",
        'text' => ':saiken:',
        'public' => true,
    ],
    [
        'code' => ':chomei:',
        'image' => "<img src='./images/memes/chomei_kun.png' style='width:64px;height:64px;' />",
        'text' => ':chomei:',
        'public' => true,
    ],
    [
        'code' => ':gyuki:',
        'image' => "<img src='./images/memes/gyuki_kun.png' style='width:64px;height:64px;' />",
        'text' => ':gyuki:',
        'public' => true,
    ],
    [
        'code' => ':kurama:',
        'image' => "<img src='./images/memes/kurama_kun.png' style='width:64px;height:64px;' />",
        'text' => ':kurama:',
        'public' => true,
    ],
    [
        'code' => ':narutoooo:',
        'image' => "<img src='./images/memes/narutoooo.png' style='width:64px;height:64px;' />",
        'text' => ':narutoooo:',
        'public' => true,
    ],
    [
        'code' => ':sasukeeee:',
        'image' => "<img src='./images/memes/sasukeeee.png' style='width:64px;height:64px;' />",
        'text' => ':sasukeeee:',
        'public' => true,
    ],
    [
        'code' => ':catjam:',
        'image' => "<img src='./images/memes/cat-jam.gif' style='width:64px;height:64px;' />",
        'text' => ':catjam:',
        'public' => true,
    ],
    [
        'code' => ':sokkatribe:',
        'image' => "<img src='./images/memes/sokkatribe.gif' />",
        'text' => ':Guess Sokka will die too:',
        'public' => true,
    ],
    [
        'code' => ':selfmedal:',
        'image' => "<img src='./images/memes/lsm_self_medal.png' />",
        'text' => ':lsm giving himself a medal:',
        'public' => true,
    ],
    [
            'code' => ':hatcloud:',
            'image' => "<img src='images/memes/hat-cloud.png' style='max-height:70px;' />",
            'text' => ':basically a neat kite:',
            'public' => true,
    ],
    [
            'code' => ':hatleaf:',
            'image' => "<img src='images/memes/hat-leaf.png'  style='max-height:70px;' />",
            'text' => ':this hat is on fiaaaahhhh',
            'public' => true,
    ],
    [
            'code' => ':hatmist:',
            'image' => "<img src='images/memes/hat-mist.png' style='max-height:70px;' />",
            'text' => ':there must be a mist opportunity here:',
            'public' => true,
    ],
    [
            'code' => ':hatsand:',
            'image' => "<img src='images/memes/hat-sand.png' style='max-height:70px;' />",
            'text' => ':i hate this hat its so coarse and it gets into everything:',
            'public' => true,
    ],
    [
            'code' => ':hatstone:',
            'image' => "<img src='images/memes/hat-stone.png'  style='max-height:70px;' />",
            'text' => ':like a rock, also makes a great pet:',
            'public' => true,
    ],
    [
            'code' => ':holdup:',
            'image' => "<img src='./images/memes/holdup.png' />",
            'text' => ':hold up:',
            'public' => true,
    ],
    [
            'code' => ':hehecat:',
            'image' => "<img src='./images/memes/hehecat.png' />",
            'text' => ':hehe cat:',
            'public' => true,
    ],
    [
            'code' => ':nothehecat:',
            'image' => "<img src='./images/memes/nothehecat.png' />",
            'text' => ':not hehe cat:',
            'public' => true,
    ],
    [
            'code' => ':sadcatthumbsup:',
            'image' => "<img src='./images/memes/sadcatthumbsup.png' />",
            'text' => ':sad cat thumbs up:',
            'public' => true,
    ],
    [
            'code' => ':whatisthis:',
            'image' => "<img src='./images/memes/tiredphone.png' />",
            'text' => ':what is this:',
            'public' => true,
    ],
    [
            'code' => ':popcorn:',
            'image' => "<img src='./images/memes/Michael-Jackson-Popcorn.gif' />",
            'text' => ':popcorn:',
            'public' => true,
    ],
    [
            'code' => ':huhh:',
            'image' => "<img src='./images/memes/HUHH.png' />",
            'text' => ':huhh:',
            'public' => true,
    ],
    [
            'code' => ':blonk:',
            'image' => "<img src='./images/memes/Blonk.png' />",
            'text' => ':blonk:',
            'public' => true,
    ],
    [
            'code' => ':mockingspongebob:',
            'image' => "<img src='./images/memes/Mocking-Spongebob.png' />",
            'text' => ':mocking spongebob:',
            'public' => true,
    ],
    [
            'code' => ':patrick:',
            'image' => "<img src='./images/memes/Patrick.png' />",
            'text' => ':patrick:',
            'public' => true,
    ],
    [
            'code' => ':handsome:',
            'image' => "<img src='./images/memes/Handsome-Squidward.png' />",
            'text' => ':handsome:',
            'public' => true,
    ],
    [
            'code' => ':dab:',
            'image' => "<img src='./images/memes/Squidward-Dab.png' />",
            'text' => ':dab:',
            'public' => true,
    ],
    [
            'code' => ':krabbypatties:',
            'image' => "<img src='images/memes/krabby-patties.png' />",
            'text' => ':krabby patties:',
            'public' => true,
    ],
    [
            'code' => ':reptar:',
            'image' => "<img src='./images/memes/Reptar.png' />",
            'text' => ':reptar:',
            'public' => true,
    ],
    [
            'code' => ':tuxedopooh:',
            'image' => "<img src='./images/memes/Tuxedo-Pooh' />",
            'text' => ':tuxedo pooh:',
            'public' => true,
    ],
    [
            'code' => ':dankjigglypuff:',
            'image' => "<img src='./images/memes/dank_jigglypuff.gif' />",
            'text' => ':dankjigglypuff:',
            'public' => true,
    ],
    [
            'code' => ':stitch:',
            'image' => "<img src='./images/memes/Stitch.gif' />",
            'text' => ':stitch:',
            'public' => true,
    ],
    [
            'code' => ':patoderp:',
            'image' => "<img src='./images/memes/Patoderp.gif' />",
            'text' => ':patoderp:',
            'public' => true,
    ],
    [
            'code' => ':banhammer:',
            'image' => "<img src='./images/memes/Banhammer.png' />",
            'text' => ':banhammer:',
            'public' => true,
    ],
    [
            'code' => ':200iq:',
            'image' => "<img src='./images/memes/200IQ.png' />",
            'text' => ':200iq:',
            'public' => true,
    ],
    [
            'code' => ':galaxybrain:',
            'image' => "<img src='./images/memes/GalaxyBrain.png' />",
            'text' => ':galaxybrain:',
            'public' => true,
    ],
    [
            'code' => ':bigbrainbobby:',
            'image' => "<img src='./images/memes/BigBrainBobby.png' />",
            'text' => ':bigbrainbobby:',
            'public' => true,
    ],
    [
        'code' => ':elmofire:',
        'image' => "<img src='./images/memes/elmo_fire.png' />",
        'text' => ':elmofire:',
        'public' => true,
    ],
    [
        'code' => ':rotenkohead:',
        'image' => "<img src='./images/memes/rotenko_head.png' />",
        'text' => ':rotenkohead:',
        'public' => true,
    ],
    [
        'code' => ':notabit:',
        'image' => "<img src='./images/memes/notabit.png' />",
        'text' => ':notabit:',
        'public' => true,
    ],
    [
        'code' => ':praisethesun:',
        'image' => "<img src='./images/memes/PraiseTheSun.png' />",
        'text' => ':praisethesun:',
        'public' => true,
    ],
    [
        'code' => ':gahorse:',
        'image' => "<img src='./images/memes/gahorse.gif' />",
        'text' => ':gahorse:',
        'public' => true,
    ],
    [
        'code' => ':smugbaka:',
        'image' => "<img src='./images/memes/smugbaka.png' />",
        'text' => ':smugbaka:',
        'public' => true,
    ],
    [
        'code' => ':cooljojo:',
        'image' => "<img src='./images/memes/cooljojo.gif' />",
        'text' => ':cooljojo:',
        'public' => true,
    ],
    [
        'code' => ':bink:',
        'image' => "<img src='./images/memes/bink.png' />",
        'text' => ':bink:',
        'public' => true,
    ],
    [
        'code' => ':lyin:',
        'image' => "<img src='./images/memes/lyin.png' />",
        'text' => ':lyin:',
        'public' => true,
    ],
    [
        'code' => ':gojo:',
        'image' => "<img src='./images/memes/gojo.png' />",
        'text' => ':gojo:',
        'public' => true,
    ],
    [
        'code' => ':sadgies:',
        'image' => "<img src='./images/memes/sadgies.png' />",
        'text' => ':sadgies:',
        'public' => true,
    ],
    [
        'code' => ':applecat:',
        'image' => "<img src='./images/memes/applecat.gif' />",
        'text' => ':applecat:',
        'public' => true,
    ],
    [
        'code' => ':happybee:',
        'image' => "<img src='./images/memes/happybee.png' />",
        'text' => ':happybee:',
        'public' => true,
    ],
    [
        'code' => ':sadbee:',
        'image' => "<img src='./images/memes/sadbee.png' />",
        'text' => ':sadbee:',
        'public' => true,
    ],
    [
        'code' => ':angrybee:',
        'image' => "<img src='./images/memes/angrybee.png' />",
        'text' => ':angrybee:',
        'public' => true,
    ],   
    [
        'code' => ':hatarena:',
        'image' => "<img src='./images/memes/hat-arena.png' />",
        'text' => ':hatarena:',
        'public' => true,
    ],       
];
