<?php


return [
    [
        'code' => ':lesiregusta:',
        'image' => ' />',
        'text' => ':like a sir gusta:',
        'public' => true,
    ],
    [
        'code' => ':lemadamgusta:',
        'image' => ' />',
        'text' => ':like a lady gusta:',
        'public' => true,
    ],
    [
        'code' => ':lol:',
        'image' => ' />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':yuno:',
        'image' => ' />',
        'text' => ':Y u no?:',
        'public' => true,
    ],
    [
        'code' => ':challengeaccepted:',
        'image' => ' />',
        'text' => ':challenge accepted:',
        'public' => true,
    ],
    [
        'code' => ':foreveralone:',
        'image' => ' />',
        'text' => ':forever alone:',
        'public' => true,
    ],
    [
        'code' => ':rageface:',
        'image' => ' />',
        'text' => ':rage face:',
        'public' => true,
    ],
    [
        'code' => ':megusta:',
        'image' => ' />',
        'text' => ':me gusta:',
        'public' => true,
    ],
    [
        'code' => ':heckyeah:',
        'image' => ' />',
        'text' => ':heck yeah:',
        'public' => true,
    ],
    [
        'code' => ':okay:',
        'image' => ' />',
        'text' => ':okay:',
        'public' => true,
    ],
    [
        'code' => ':screwthis:',
        'image' => ' />',
        'text' => ':screw this:',
        'public' => true,
    ],
    [
        'code' => ':skyrimstan:',
        'image' => ' />',
        'text' => ':skyrim stan:',
        'public' => true,
    ],
    [
        'code' => ':asianfather:',
        'image' => ' />',
        'text' => ':asian father:',
        'public' => true,
    ],
    [
        'code' => ':iknowthatfeel:',
        'image' => ' />',
        'text' => ':i know that feel:',
        'public' => true,
    ],
    [
        'code' => ':skeptical:',
        'image' => ' />',
        'text' => ':skeptical:',
        'public' => true,
    ],
    [
        'code' => ':truestory:',
        'image' => ' />',
        'text' => ':true story:',
        'public' => true,
    ],
    [
        'code' => ':pokerface:',
        'image' => ' />',
        'text' => ':poker face:',
        'public' => true,
    ],
    [
        'code' => ':awwyeah:',
        'image' => ' />',
        'text' => ':aww yeah:',
        'public' => true,
    ],
    [
        'code' => ':ohgodwhy:',
        'image' => ' />',
        'text' => ':oh god why:',
        'public' => true,
    ],
    [
        'code' => ':wut:',
        'image' => ' />',
        'text' => ':wut:',
        'public' => true,
    ],
    [
        'code' => ':areyouserious:',
        'image' => ' />',
        'text' => ':are you serious:',
        'public' => true,
    ],
    [
        'code' => ':lololort:',
        'image' => '<img src="../images/memes/reverse_lol.png" />',
        'text' => ':lol:',
        'public' => true,
    ],
    [
        'code' => ':likeasir:',
        'image' => ' />',
        'text' => ':like a sir:',
        'public' => true,
    ],
    [
        'code' => ':likealady:',
        'image' => ' />',
        'text' => ':like a lady:',
        'public' => true,
    ],
    [
        'code' => ':allofthe:',
        'image' => ' />',
        'text' => ':all of the:',
        'public' => true,
    ],
    [
        'code' => ':grumpycat:',
        'image' => ' />',
        'text' => ':grumpy cat:',
        'public' => true,
    ],
    [
        'code' => ':notbad:',
        'image' => ' />',
        'text' => ':not bad:',
        'public' => true,
    ],
    [
        'code' => ':whathasbeenseen:',
        'image' => ' />',
        'text' => ':what has been seen:',
        'public' => true,
    ],
    [
        'code' => ':no:',
        'image' => ' />',
        'text' => ':no:',
        'public' => true,
    ],
    [
        'code' => ':motherofgod:',
        'image' => ' />',
        'text' => ':mother of god:',
        'public' => true,
    ],
    [
        'code' => ':creepygusta:',
        'image' => ' />',
        'text' => ':creepy gusta:',
        'public' => true,
    ],
    [
        'code' => ':whatthe:',
        'image' => ' />',
        'text' => ':what the:',
        'public' => true,
    ],
    [
        'code' => ':insanitywolf:',
        'image' => ' />',
        'text' => ':insanity wolf:',
        'public' => true,
    ],
    [
        'code' => ':why:',
        'image' => ' />',
        'text' => ':why:',
        'public' => true,
    ],
    [
        'code' => ':yoda:',
        'image' => ' />',
        'text' => ':yoda:',
        'public' => true,
    ],
    [
        'code' => ':alot:',
        'image' => ' />',
        'text' => ':alot:',
        'public' => true,
    ],
    [
        'code' => ':herpderp:',
        'image' => ' />',
        'text' => ':herp derp:',
        'public' => true,
    ],
    [
        'code' => ':doge:',
        'image' => ' />',
        'text' => ':doge:',
        'public' => true,
    ],
    [
        'code' => ':catte:',
        'image' => ' />',
        'text' => ':catte:',
        'public' => true,
    ],
    [
        'code' => ':confessionbear:',
        'image' => ' />',
        'text' => ':confession bear:',
        'public' => true,
    ],
    [
        'code' => ':kappa:',
        'image' => ' />',
        'text' => ':kappa:',
        'public' => true,
    ],
    [
        'code' => ':howaboutno:',
        'image' => ' />',
        'text' => ':how about no:',
        'public' => true,
    ],
    [
        'code' => ':awkwardseal:',
        'image' => ' />',
        'text' => ':awkward seal:',
        'public' => true,
    ],
    [
        'code' => ':wegotabadass:',
        'image' => ' />',
        'text' => ':watch out we got a badass here:',
        'public' => true,
    ],
    [
        'code' => ':facepalm:',
        'image' => ' />',
        'text' => ':facepalm:',
        'public' => true,
    ],
    [
        'code' => ':opieop:',
        'image' => ' />',
        'text' => ':opieop:',
        'public' => true,
    ],
    [
        'code' => ':oskomodo:',
        'image' => ' />',
        'text' => ':oskomodo:',
        'public' => true,
    ],
    [
        'code' => ':babyrage:',
        'image' => ' />',
        'text' => ':babyrage:',
        'public' => true,
    ],
    [
        'code' => ':pogchamp:',
        'image' => ' />',
        'text' => ':pogchamp:',
        'public' => true,
    ],
    [
        'code' => ':smileyderp:',
        'image' => ' />',
        'text' => ':smileyderp:',
        'public' => true,
    ],
    [
        'code' => ':aliensguy:',
        'image' => ' />',
        'text' => ':aliensguy:',
        'public' => true,
    ],
    [
        'code' => ':kreygasm:',
        'image' => ' />',
        'text' => ':kreygasm:',
        'public' => true,
    ],
    [
        'code' => ':seemsgood:',
        'image' => ' />',
        'text' => ':seems good:',
        'public' => true,
    ],
    [
        'code' => ':vaultboy:',
        'image' => ' />',
        'text' => ':vault boy:',
        'public' => true,
    ],
    [
        'code' => ':heyguys:',
        'image' => ' />',
        'text' => ':hey guys:',
        'public' => true,
    ],
    [
        'code' => ':4head:',
        'image' => ' />',
        'text' => ':4head:',
        'public' => true,
    ],
    [
        'code' => ':tellmemore:',
        'image' => ' />',
        'text' => ':tell me more:',
        'public' => true,
    ],
    [
        'code' => ':victory:',
        'image' => ' />',
        'text' => ':victory:',
        'public' => true,
    ],
    [
        'code' => ':everywhere:',
        'image' => ' />',
        'text' => ':everywhere:',
        'public' => true,
    ],
    [
        'code' => ':notlikethis:',
        'image' => ' />',
        'text' => ':not like this:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodman:',
        'image' => ' />',
        'text' => ':feels good man:',
        'public' => true,
    ],
    [
        'code' => ':feelsbadman:',
        'image' => ' />',
        'text' => ':feels bad man:',
        'public' => true,
    ],
    [
        'code' => ':feelsgoodbad:',
        'image' => ' />',
        'text' => ':feels good bad:',
        'public' => true,
    ],
    [
        'code' => ':confused:',
        'image' => ' />',
        'text' => ':confused:',
        'public' => true,
    ],
    [
        'code' => ':letsrumble:',
        'image' => ' />',
        'text' => ':letsrumble:',
        'public' => true,
    ],
    [
        'code' => ':thisisfine:',
        'image' => ' />\'',
        'text' => ':this is fine:',
        'public' => true,
    ],

    [
        'code' => ':notmybusiness:',
        'image' => ' />\'',
        'text' => ':none of my business:',
        'public' => true,
    ],
    [
        'code' => ':youdontsay:',
        'image' => ' />\'',
        'text' => ':you don\'t say:',
        'public' => true,
    ],
    [
        'code' => ':callinglsm:',
        'image' => '<img src="../images/memes/arctic6.png" />',
        'text' => ':calling lsm:',
        'public' => true,
    ],
    [
        'code' => ':guessilldie:',
        'image' => '<img src="../images/memes/feels_old_man.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':surprisedpikachu:',
        'image' => '<img src="../images/memes/surprised_pikachu.png" />',
        'text' => ':surprised pikachu:',
        'public' => true,
    ],
    [
        'code' => ':whitelotus:',
        'image' => '<img src="../images/memes/iroh.png" />',
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':dogekek:',
        'image' => "<img src='../images/memes/doge_kek.png' style='width:64px;height:64px;' />",
        'text' => ':guess I\'ll die:',
        'public' => true,
    ],
    [
        'code' => ':feelschatman:',
        'image' => "<img src='../images/memes/feelschatman.png' style='width:64px;height:64px;' />",
        'text' => ':feelschatman:',
        'public' => true,
    ],
];
