name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.prettier_test }}
        # This is important to fetch the changes to the previous commit
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,php}
        prettier_plugins: "@prettier/plugin-php"
        only_changed: true
